frase = (input('Insira a frase para que ela possa ser traduzida na linguagem de Leet: '))
frase = frase.upper()
frase = frase.replace('A', '4')
frase = frase.replace('E', '3')
frase = frase.replace('G', '6')
frase = frase.replace('H', '#')
frase = frase.replace('I', '!')
frase = frase.replace('L', '|')
frase = frase.replace('O', '0')
frase = frase.replace('S', '$')
frase = frase.replace('T', '7')
frase = frase.replace('U', 'ü')
print(frase)
